### PR TITLE
Added new props called backgroundColor which sets the backgroundColor of the signature

### PR DESCRIPTION
**Pull request by john1jan**
+ Added three new props for setting strokeColor, minStrokeWidth and maxStrokeWidth
+ Added new props called **backgroundColor** which takes any color string which supports  #RRGGBB #AARRGGBB 'red', 'blue', 'green', 'black', 'white', 'gray', 'cyan', 'magenta', 'yellow', 'lightgray', 'darkgray'
+ Add feature for setting background as transparent. just set backgroundColor="transparent". 
+ Removed showBorder as its not required the developer can set border for the container of this component
+ Added a example project as well to use and added demo screenshots as well

This feature is only done in android. I need some one's help to do it on ios.
Tested on android it works great. 

Fixed some of the issues with example as it was not compiling in android
@jedt please check it and merge

### CODE REVIEW

**Comment by john1jan** [comment]
@jedt @theinventor any update on this PR?

**Comment by luskin** [comment]
Can we get this in?

**Comment by john1jan** [comment]
@jedt @theinventor can you check this PR

**Comment by zerobytes** [comment]
Hey @john1jan, I'm thinking that if the default background is transparent, there would be no need to haveall those options of colors. Transparent would suffice, for all cases, once you could just set the background of the wrapping component to whatever you need.

**Comment by john1jan** [comment]
i have updated the PR please check

**Comment by john1jan** [comment]
@jedt @theinventor

**Review by LazaDaniel — APPROVED** [review]

**Comment by jedt** [comment]
merged with https://github.com/RepairShopr/react-native-signature-capture/pull/216

**Pull request closed without merging**
