### PR TITLE
Fix compatibility for RN 0.47

### PR DESCRIPTION
**Pull request by elieteyssedou**

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
@jedt this PR is necessary to run the app with react native >= 0.47
without it the library cannot be used.
I have tested the changes on android and I can confirm that the app works with RN 0.47

**Comment by fabriziomoscon** [comment]
great!

**Comment by fabriziomoscon** [comment]
@jedt could you also publish on npm?

**Comment by jedt** [comment]
Published. Thanks!

**Pull request merged**
