### PR TITLE
Require UIManager from React

### PR DESCRIPTION
**Pull request by nikor**

### CODE REVIEW

**Comment by john1jan** [comment]
Is this working in IOS ?

**Comment by zoontek** [comment]
@john1jan It's working on iOS.

But everything else on the master branch don't (on iOS: onChange() is never fired, save reset the signature, etc)
Had it been merged without any test?

**Comment by john1jan** [comment]
Its was tested in Android.

**Comment by zoontek** [comment]
Can you wrap all the changes with a Platform test to prevent breaking iOS malfunction? Thanks

https://facebook.github.io/react-native/docs/platform-specific-code.html

**Comment by zoontek** [comment]
Actually, it doesn't work on Android either:

**Pull request merged**
