### PR TITLE
Added new props saveImageFileInExtStorage,showNativeButtons,viewMode …

### PR DESCRIPTION
**Pull request by john1jan**
Added new props **saveImageFileInExtStorage,showNativeButtons,viewMode** and added methods for saving and reseting image from react js code

Updated ReadMe reflecting the changes.

Working awesome in **android** .Not tested for IOS.

### CODE REVIEW

**Comment by theinventor** [comment]
Hey - thanks! 

Hoping other android users can comment too..

Do you think saveImageFile makes sense in the library? Couldn't that be app code just as easily?

We'll review in more detail shortly!

**Comment by john1jan** [comment]
do you mean saveImageFileInExtStorage props ? or saveImage() method ?

**Comment by john1jan** [comment]
You want me to change anything or it is good to go for merge ?

**Comment by theinventor** [comment]
Sorry - we usually take a few weeks because  we work this in between our sprints, we can test in a week or so - sorry for the wait!


Troy Anderson

**Comment by jedt** [comment]
Hey @john1jan thanks but can you reduce the file changes like resubmit without the intelliJ idea builds?

**Comment by john1jan** [comment]
ok, will do it in short while

**Comment by john1jan** [comment]
done.

**Comment by jedt** [comment]
Merged. Thanks @john1jan!

**Pull request merged**
